config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get "/register", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  get "/pin", to: "sessions#pin"
  post "/pin", to: "sessions#pin"

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end
    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end
  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:create, :show, :edit, :update]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include VoteableJasonNov

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find_by(slug: params[:post_id])
    @comment = @post.comments.new(params.require(:comment).permit(:body))
    @comment.creator = current_user

    if @comment.save
      flash[:notice] = "Your comment was successfully created!"
      redirect_to @post
    else
      @post.comments.reload # drops the incomplete comment before re-rendering
      render "posts/show"
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.find_by(creator: current_user, voteable: @comment)  # get the users existing vote (if exists)

    if @vote  # if user has already vote on this object, update existing vote
      @vote.update(vote: params[:vote], creator: current_user, voteable: @comment)
      @message_text = "Vote updated!"
    else  # create new vote if no existing vote
      @vote = Vote.create(vote: params[:vote], creator: current_user, voteable: @comment)
      @message_text = "Vote received!"
    end

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end
end

app/views/comments/_comments.html.erb
<% show_post_link ||= false %>

<div class="row">
  <div class="well span1 text-center">
      <% if logged_in? %>
        <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: "post", remote: true do %>
          <i class="icon-chevron-up"></i>
        <% end %>
      <% end %>
    <div>
      <span id="comment_<%= comment.id %>_votes"><%= comment.total_votes %> votes</span>
    </div>
      <% if logged_in? %>
        <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: "post", remote: true do %>
        <i class="icon-chevron-down"></i>
        <% end %>
      <% end %>
  </div>

  <div class="well span9">
    <p>
      <em>"<%= comment.body %>"</em>
    </p>
    <small class="quiet">
      Posted by: <%= link_to comment.creator.username, user_path(comment.creator) %>
      on <%= format_date_time(comment.created_at) %>
      <% if show_post_link %>
        <span class="pull-right">Related post: <%= link_to comment.post.title, post_path(comment.post) %></span>
      <% end %>
    </small>
  </div>
</div>

app/views/comments/vote.js.erb
$("#comment_<%= @comment.id %>_votes").html("<%= @comment.total_votes %> votes");

// display confirmation then fade out
$("#js_vote_message span").html("<%= @message_text %>");
document.getElementById("js_vote_message").style.display = "block";
$("#js_vote_message").delay(3200).fadeOut();