config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get "/register", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  get "/pin", to: "sessions#pin"
  post "/pin", to: "sessions#pin"

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end
    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end
  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:create, :show, :edit, :update]
end

app/models/post.rb
class Post < ActiveRecord::Base
  include VoteableJasonNov
  include SluggableJasonNov

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 2}
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true

  sluggable_column :title
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  POSTS_PER_PAGE = 5

  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user_or_admin, only: [:edit, :update]

  def index
    @posts = Post.all
    if @posts
      sorted_posts = @posts.all.sort_by { |post| post.total_votes }.reverse
      @pages = (@posts.size.to_f / POSTS_PER_PAGE).ceil
      @current_page = (params[:offset].to_i / POSTS_PER_PAGE) + 1
      @posts = sorted_posts[params[:offset].to_i, POSTS_PER_PAGE]
    end
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = "Your post was successfully created!"
      redirect_to post_path(@post)  # or just @post
    else
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = "Your post was successfully updated!"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    vote = Vote.find_by(creator: current_user, voteable: @post)  # get the users existing vote (if exists)

    if vote  # if user has already vote on this object, update existing vote
      vote.update(vote: params[:vote], creator: current_user, voteable: @post)
      @message_text = "Vote updated!"
    else  # create new vote if no existing vote
      vote = Vote.create(vote: params[:vote], creator: current_user, voteable: @post)
      @message_text = "Vote received!"
    end

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  private

  def post_params
    params.require(:post).permit(:url, :title, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by(slug: params[:id])
  end

  def require_same_user
    access_denied unless logged_in? && current_user == @post.creator
  end

  def require_same_user_or_admin
    access_denied unless logged_in? && (current_user == @post.creator || logged_in? && current_user.admin?)
  end
end

app/views/posts/_form.html.erb
<%= render "/shared/errors", obj: @post %>

<div class="well">
  <%= form_for @post do |f| %>
    <div class="control-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="control-group">
      <%= f.label :url, "URL" %>
      <%= f.text_field :url %>
    </div>
    <div class="control-group">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5, class: "span8" %>
    </div>
    <div class="control-group">
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <% cb.label(class: "checkbox inline") { cb.check_box(class: "checkbox") + cb.text } %>
      <% end %>
    </div>
    <%= f.submit(@post.new_record? ? "Create Post" : "Submit Changes", class: "btn btn-primary") %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="row">
  <div class="well span1 text-center">
      <% if logged_in? %>
        <%= link_to vote_post_path(post, vote: true), method: "post", remote: true do %>
          <i class="icon-chevron-up"></i>
        <% end %>
      <% end %>
    <div>
      <span id="post_<%= post.id %>_votes"><%= post.total_votes %> votes</span>
    </div>
      <% if logged_in? %>
        <%= link_to vote_post_path(post, vote: false), method: "post", remote: true do %>
        <i class="icon-chevron-down"></i>
        <% end %>
      <% end %>
  </div>

  <div class='well span9'>
    <%= render "/shared/edit_button", post: post %>
    <%= render post.categories %>
    <h4><%= link_to post.title, post_path(post) %></h4>
    <p><%= post.description %></p>
    <p class="quiet"><small>
      Posted by: <%= link_to post.creator.username, user_path(post.creator) %>
      on <%= format_date_time(post.created_at) %>
    </small></p>
    <small><%= link_to "#{post.comments.size} Comments", post_path(post) %></small>
  </div>
</div>

app/views/posts/_post_form.html.erb
<%= render "/shared/errors", obj: @post %>

<div class="well">
  <%= form_for @post do |f| %>

    <div class="control-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="control-group">
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>

    <div class="control-group">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5, class: "span8" %>
    </div>

    <div class="control-group">
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <% cb.label(class: "checkbox inline") { cb.check_box(class: "checkbox") + cb.text } %>
      <% end %>
    </div>

    <%= f.submit(@post.new_record? ? "Create Post" : "Submit Changes", class: "btn btn-primary") %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render "/shared/content_title", title: "Edit Post" %>
<%= render "form" %>

app/views/posts/index.html.erb
<%= render "/shared/content_title", title: "All Posts" %>

<% @posts.each do |post| %>
  <%= %>
  <%= render "post", post: post %>
<% end %>

<hr/>

<div class="button_group_wrap">
  <div class="btn-group btn_group_center">
    <% @pages.times do |n| %>
      <% if @current_page == n + 1 %>
        <span class="btn quiet">
          <%= "Page #{n + 1}" %>
        </span>
      <% else %>
        <span class="btn">
          <%= link_to "Page #{n + 1}", posts_path(offset: n * PostsController::POSTS_PER_PAGE) %>
        </span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<%= render "/shared/content_title", title: "Create New Post" %>
<%= render "form" %>

app/views/posts/show.html.erb
<%= render "/shared/edit_button", post: @post %>
<p><%= render @post.categories %><p>
<p class="lead"><%= link_to @post.title, fix_url(@post.url) %></p>
<hr/>
<p><%= @post.description %></p>

<hr/>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <%= render "/shared/errors", obj: @comment %>
    <div class="control-group">
      <%= f.label :body, "Leave a comment below..." %>
      <%= f.text_area :body, rows: 5, class: "span6" %>
    </div>
    <%= f.submit "Create Comment", class: "btn btn-primary" %>
  <% end %>
<% end %>

<br/>

<h5>Previous comments:</h5>

<% sort_by_total_votes(@post.comments).each do |comment| %>
  <%= render "comments/comments", comment: comment %>
<% end %>

app/views/posts/vote.js.erb
$('#post_<%= @post.id %>_votes').html('<%= @post.total_votes %> votes');

// display confirmation then fade out
$("#js_vote_message span").html("<%= @message_text %>");
document.getElementById("js_vote_message").style.display = "block";
$("#js_vote_message").delay(3200).fadeOut();